default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_music_dev

test:
  <<: *default
  database: pai_music_test

production:
  <<: *default
  username: <%= ENV["PAI_MUSIC_DATABASE_USERNAME"] %>
  password: <%= ENV["PAI_MUSIC_DATABASE_PASSWORD"] %>
  host: <%= ENV["PAI_MUSIC_DATABASE_HOST"] %>
  database: <%= ENV["PAI_MUSIC_DATABASE"] %>
